
-- RESET BASIC TABLES
TRUNCATE TABLE ACTIVATION_CODE;
TRUNCATE TABLE FORGET_PASSWORD;
TRUNCATE TABLE DATABASECHANGELOG;

TRUNCATE TABLE USER_COMMENT;
TRUNCATE TABLE USER_EXT;
TRUNCATE TABLE USER_GROUP;
TRUNCATE TABLE USER_GROUP_MEMBER;
TRUNCATE TABLE USER_GROUP_ROLE;
TRUNCATE TABLE USER_INFO;
TRUNCATE TABLE USER_MESSAGE;
TRUNCATE TABLE USER_OP_LOG;
TRUNCATE TABLE USER_ROLE;
TRUNCATE TABLE USER_STATE;

DELETE FROM ROLE WHERE TENANT_ID>0;
DELETE FROM ROLE_FUNC_PERMISSION WHERE TENANT_ID>0;

-- RESET ASSISTANT TABLES
TRUNCATE TABLE AFFICHE;
TRUNCATE TABLE ATTACHMENT;
TRUNCATE TABLE DOCUMENT;
TRUNCATE TABLE FEEDBACK;
TRUNCATE TABLE SMS_IN;
TRUNCATE TABLE SMS_OUT;
TRUNCATE TABLE TAG;

-- RESET PERSONAL TABLES
TRUNCATE TABLE CALENDAR;
TRUNCATE TABLE CONTACTS;
TRUNCATE TABLE CONTACTS_GROUP;
TRUNCATE TABLE CONTACTS_GROUP_MEMBER;
TRUNCATE TABLE NOTE;
TRUNCATE TABLE TODO;

-- RESET CRM TABLES
TRUNCATE TABLE CUST_ACTIVITY;
TRUNCATE TABLE CUST_CONTACTS;
TRUNCATE TABLE CUST_EVENT;
TRUNCATE TABLE CUSTOMER;
TRUNCATE TABLE CUSTOMER_FEATURE;
TRUNCATE TABLE CUSTOMER_STATE;
 
