package com.litt.saap.system.po;

/**
 * Func generated by MyEclipse Persistence Tools
 */

public class Func implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer moduleId;

	private String funcCode;

	private Integer funcType;

	private String funcName;

	// Constructors

	/** default constructor */
	public Func()
	{
	}

	/** full constructor */
	public Func(Integer moduleId, String funcCode, Integer funcType, String funcName)
	{
		this.moduleId = moduleId;
		this.funcCode = funcCode;
		this.funcType = funcType;
		this.funcName = funcName;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getModuleId()
	{
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId)
	{
		this.moduleId = moduleId;
	}

	public String getFuncCode()
	{
		return this.funcCode;
	}

	public void setFuncCode(String funcCode)
	{
		this.funcCode = funcCode;
	}

	public Integer getFuncType()
	{
		return this.funcType;
	}

	public void setFuncType(Integer funcType)
	{
		this.funcType = funcType;
	}

	public String getFuncName()
	{
		return this.funcName;
	}

	public void setFuncName(String funcName)
	{
		this.funcName = funcName;
	}

}