package com.litt.saap.system.po;

/**
 * Menu generated by MyEclipse Persistence Tools
 */

public class Menu implements java.io.Serializable
{

	// Fields

	private Integer menuId;

	private String menuCode;

	private String menuName;

	private String menuUrl;

	private int parentId;
	
	private Integer leftNum;
	
	private Integer rightNum;

	private boolean isLeaf;

	private int status;

	private int position;
	
	private String iconUrl;
	
	private String imageUrl;

	private String remark;

	// Constructors

	/** default constructor */
	public Menu()
	{
	}

	/** full constructor */
	public Menu(String menuCode, String menuName, String menuUrl, int parentId, boolean isLeaf, int status,
			int position, String remark)
	{
		this.menuCode = menuCode;
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.parentId = parentId;
		this.isLeaf = isLeaf;
		this.status = status;
		this.position = position;
		this.remark = remark;
	}

	// Property accessors

	public Integer getMenuId()
	{
		return this.menuId;
	}

	public void setMenuId(Integer menuId)
	{
		this.menuId = menuId;
	}

	public String getMenuCode()
	{
		return this.menuCode;
	}

	public void setMenuCode(String menuCode)
	{
		this.menuCode = menuCode;
	}

	public String getMenuName()
	{
		return this.menuName;
	}

	public void setMenuName(String menuName)
	{
		this.menuName = menuName;
	}

	public String getMenuUrl()
	{
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl)
	{
		this.menuUrl = menuUrl;
	}

	public int getParentId()
	{
		return this.parentId;
	}

	public void setParentId(int parentId)
	{
		this.parentId = parentId;
	}

	public boolean getIsLeaf()
	{
		return this.isLeaf;
	}

	public void setIsLeaf(boolean isLeaf)
	{
		this.isLeaf = isLeaf;
	}

	public int getStatus()
	{
		return this.status;
	}

	public void setStatus(int status)
	{
		this.status = status;
	}

	public int getPosition()
	{
		return this.position;
	}

	public void setPosition(int position)
	{
		this.position = position;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * @return the leftNum.
	 */
	protected Integer getLeftNum()
	{
		return leftNum;
	}

	/**
	 * @param leftNum the leftNum to set.
	 */
	protected void setLeftNum(Integer leftNum)
	{
		this.leftNum = leftNum;
	}

	/**
	 * @return the rightNum.
	 */
	protected Integer getRightNum()
	{
		return rightNum;
	}

	/**
	 * @param rightNum the rightNum to set.
	 */
	protected void setRightNum(Integer rightNum)
	{
		this.rightNum = rightNum;
	}

	/**
	 * @return the iconUrl
	 */
	public String getIconUrl() {
		return iconUrl;
	}

	/**
	 * @param iconUrl the iconUrl to set
	 */
	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}

	/**
	 * @return the imageUrl
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * @param imageUrl the imageUrl to set
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

}