package com.litt.saap.system.po;

/**
 * Module generated by MyEclipse Persistence Tools
 */

public class Module implements java.io.Serializable
{

	// Fields

	private Integer moduleId;

	private String moduleCode;

	private String moduleName;

	private int parentId;

	private boolean isLeaf;

	private int status;

	// Constructors

	/** default constructor */
	public Module()
	{
	}

	/** full constructor */
	public Module(String moduleCode, String moduleName, int parentId, boolean isLeaf, int status)
	{
		this.moduleCode = moduleCode;
		this.moduleName = moduleName;
		this.parentId = parentId;
		this.isLeaf = isLeaf;
		this.status = status;
	}

	// Property accessors

	public Integer getModuleId()
	{
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId)
	{
		this.moduleId = moduleId;
	}

	public String getModuleCode()
	{
		return this.moduleCode;
	}

	public void setModuleCode(String moduleCode)
	{
		this.moduleCode = moduleCode;
	}

	public String getModuleName()
	{
		return this.moduleName;
	}

	public void setModuleName(String moduleName)
	{
		this.moduleName = moduleName;
	}

	public int getParentId()
	{
		return this.parentId;
	}

	public void setParentId(int parentId)
	{
		this.parentId = parentId;
	}

	public boolean getIsLeaf()
	{
		return this.isLeaf;
	}

	public void setIsLeaf(boolean isLeaf)
	{
		this.isLeaf = isLeaf;
	}

	public int getStatus()
	{
		return this.status;
	}

	public void setStatus(int status)
	{
		this.status = status;
	}

}