ALTER TABLE USER_GROUP CHANGE CREATE_USER_ID CREATE_BY INT NOT NULL;
ALTER TABLE USER_GROUP CHANGE UPDATE_USER_ID UPDATE_BY INT NOT NULL;

ALTER TABLE USER_GROUP_MEMBER DROP COLUMN TYPE;
ALTER TABLE USER_GROUP_MEMBER DROP COLUMN STATUS;
ALTER TABLE USER_GROUP_MEMBER ADD CREATE_BY INT NOT NULL;

ALTER TABLE ROLE ADD CREATE_BY            INT NOT NULL COMMENT '创建用户';
ALTER TABLE ROLE ADD CREATE_DATETIME      DATETIME NOT NULL COMMENT '创建时间';
ALTER TABLE ROLE ADD UPDATE_BY            INT NOT NULL COMMENT '更新人';
ALTER TABLE ROLE ADD UPDATE_DATETIME      DATETIME NOT NULL COMMENT '更新时间';

ALTER TABLE USER_ROLE ADD CREATE_BY            INT NOT NULL COMMENT '创建用户';
ALTER TABLE USER_ROLE ADD CREATE_DATETIME      DATETIME NOT NULL COMMENT '创建时间';
ALTER TABLE USER_GROUP_ROLE ADD CREATE_BY            INT NOT NULL COMMENT '创建用户';
ALTER TABLE USER_GROUP_ROLE ADD CREATE_DATETIME      DATETIME NOT NULL COMMENT '创建时间';