ALTER TABLE DICT_PARAM_TYPE CHANGE DICT_TYPE DICT_TYPE VARCHAR(50) NOT NULL;
ALTER TABLE DICT_PARAM CHANGE DICT_TYPE DICT_TYPE VARCHAR(50) NOT NULL;
ALTER TABLE TENANT_DICT_PARAM CHANGE DICT_TYPE DICT_TYPE VARCHAR(50) NOT NULL;