ALTER TABLE TENANT DROP COLUMN CODE;
ALTER TABLE TENANT CHANGE APP_CODE TENANT_CODE varchar(50) NOT NULL COMMENT '租户编号';
ALTER TABLE TENANT CHANGE APP_ALIAS TENANT_ALIAS varchar(100) NOT NULL COMMENT '租户别名';