ALTER TABLE CUSTOMER ADD COLUMN PAYMENT_DAYS         INT NOT NULL DEFAULT 0 COMMENT '账期';
ALTER TABLE CUSTOMER ADD COLUMN MAILING_ADDRESS      VARCHAR(400) COMMENT '发票邮寄地址';
ALTER TABLE CUSTOMER ADD COLUMN BILLING_ADDRESS      VARCHAR(400) COMMENT '开票地址';
ALTER TABLE CUSTOMER ADD COLUMN BILLING_FULL_NAME    VARCHAR(100) COMMENT '开票全称';
ALTER TABLE CUSTOMER ADD COLUMN BANK_NAME            VARCHAR(100) COMMENT '银行名称';
ALTER TABLE CUSTOMER ADD COLUMN ACCOUNT_NO           VARCHAR(100) COMMENT '帐号';
ALTER TABLE CUSTOMER ADD COLUMN TAX_NO               VARCHAR(100) COMMENT '税号';
ALTER TABLE CUSTOMER ADD COLUMN BILLING_NOTICE       VARCHAR(2000) COMMENT '开票注意点';