<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
<meta http-equiv="Cache-Control" content="no-store"/>
<meta http-equiv="Pragma" content="no-cache"/>
<meta http-equiv="Expires" content="0"/> 
<!-- 先加载样式 -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<!--basic styles-->

	<link href="${contextPath}/<s:theme code='path'/>/css/bootstrap.min.css" rel="stylesheet" />
	<link href="${contextPath}/<s:theme code='path'/>/css/bootstrap-responsive.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="${contextPath}/<s:theme code='path'/>/css/font-awesome.min.css" />

	<!--[if IE 7]>
	  <link rel="stylesheet" href="${contextPath}/<s:theme code='path'/>/css/font-awesome-ie7.min.css" />
	<![endif]-->

	<!--page specific plugin styles-->
	<!--fonts-->

	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

	<!--ace styles-->

	<link rel="stylesheet" href="${contextPath}/<s:theme code='path'/>/css/ace.min.css" />
	<link rel="stylesheet" href="${contextPath}/<s:theme code='path'/>/css/ace-responsive.min.css" />
	<link rel="stylesheet" href="${contextPath}/<s:theme code='path'/>/css/ace-skins.min.css" />

	<!--[if lte IE 8]>
	  <link rel="stylesheet" href="${contextPath}/<s:theme code='path'/>/css/ace-ie.min.css" />
	<![endif]-->

	<!--inline styles related to this page-->

	<!--ace settings handler-->

	<script src="${contextPath}/<s:theme code='path'/>/js/ace-extra.min.js"></script>	

